### ISSUE TITLE
New emulator profiles to add to definitions (bsnes, Mesen-S and melonDS)

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#1380]
I noticed there were definitions for the retroarch cores but not for the standalone versions so I made them.

```
- Name: bsnes
  Website: 'https://bsnes.byuu.org/'
  Profiles:
    - Name: Default
      DefaultArguments: '"{ImagePath}"'
      Platforms: [Super Nintendo Entertainment System]
      ImageExtensions: [sfc, smc, zip]
      ExecutableLookup: ^bsnes\.exe

- Name: Mesen-S
  Website: 'https://github.com/SourMesen/Mesen-S'
  Profiles:
    - Name: Default
      DefaultArguments: '"{ImagePath}"'
      Platforms: [Super Nintendo Entertainment System]
      ImageExtensions: [sfc, smc, zip, 7z]
      ExecutableLookup: ^Mesen-S\.exe

- Name: melonDS
  Website: 'http://melonds.kuribo64.net/'
  Profiles:
    - Name: Default
      DefaultArguments: '"{ImagePath}"'
      Platforms: [Nintendo DS]
      ImageExtensions: [nds]
      ExecutableLookup: ^melonDS\.exe

```

I also attach a text file with the definitions.

[Definitions (bsnes, melonDS and Mesen-S).txt](https://github.com/JosefNemec/Playnite/files/3512593/Definitions.bsnes.melonDS.and.Mesen-S.txt)

edit: some fixes :/
