### ISSUE TITLE
Higan multi-emu profile to add to definitions file

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#1381]
I made the definition for each of the emulated systems in higan

```
- Name: higan
  Website: 'https://higan.byuu.org/'
  Profiles:
    - Name: Nintendo - Famicom
      DefaultArguments: '"{ImagePath}"'
      Platforms: [Nintendo Entertainment System]
      ImageExtensions: [zip, nes]  
      ExecutableLookup: ^higan.*\.exe$

    - Name: Nintendo - Super Famicom
      DefaultArguments: '"{ImagePath}"'
      Platforms: [Super Nintendo Entertainment System, Nintendo Sufami Turbo, Nintendo Satellaview]
      ImageExtensions: [sfc, smc, bs, zip] 
      ExecutableLookup: ^higan.*\.exe$

    - Name: Nintendo - Game Boy
      DefaultArguments: '"{ImagePath}"'
      Platforms: [Nintendo Game Boy]
      ImageExtensions: [zip, gb] 
      ExecutableLookup: ^higan.*\.exe$

    - Name: Nintendo - Game Boy Color
      DefaultArguments: '"{ImagePath}"'
      Platforms: [Nintendo Game Boy Color]
      ImageExtensions: [zip, gbc] 
      ExecutableLookup: ^higan.*\.exe$

    - Name: Nintendo - Game Boy Advance
      DefaultArguments: '"{ImagePath}"'
      Platforms: [Nintendo Game Boy Advance]
      ImageExtensions: [zip, gba] 
      ExecutableLookup: ^higan.*\.exe$

    - Name: Sega - Master System
      DefaultArguments: '"{ImagePath}"'
      Platforms: [Sega Master System]
      ImageExtensions: [zip, sms] 
      ExecutableLookup: ^higan.*\.exe$

    - Name: Sega - Mega Drive
      DefaultArguments: '"{ImagePath}"'
      Platforms: [Sega Genesis]
      ImageExtensions: [zip, bin, smd, md] 
      ExecutableLookup: ^higan.*\.exe$

    - Name: Sega - Game Gear
      DefaultArguments: '"{ImagePath}"'
      Platforms: [Sega Game Gear]
      ImageExtensions: [zip, gg] 
      ExecutableLookup: ^higan.*\.exe$

    - Name: NEC - PC Engine
      DefaultArguments: '"{ImagePath}"'
      Platforms: [NEC TurboGrafx 16]
      ImageExtensions: [zip, pce] 
      ExecutableLookup: ^higan.*\.exe$

    - Name: NEC - Supergrafx
      DefaultArguments: '"{ImagePath}"'
      Platforms: [NEC PC Engine SuperGrafx, NEC TurboGrafx-CD]
      ImageExtensions: [zip, cue, ccd, chd] 
      ExecutableLookup: ^higan.*\.exe$

    - Name: Bandai - WonderSwan
      DefaultArguments: '"{ImagePath}"'
      Platforms: [Bandai WonderSwan]
      ImageExtensions: [zip, ws] 
      ExecutableLookup: ^higan.*\.exe$

    - Name: Bandai - WonderSwan Color
      DefaultArguments: '"{ImagePath}"'
      Platforms: [Bandai WonderSwan Color]
      ImageExtensions: [zip, wsc] 
      ExecutableLookup: ^higan.*\.exe$
```

I also attach the text file

[Higan Profile.txt](https://github.com/JosefNemec/Playnite/files/3512595/Higan.Profile.txt)

Also while testing I notice that for some reason, the `Nintendo Satellaview`  is not checked as a supported platform for the `Nintendo - Super Famicom` profile even though I added it and named it exactly as another existing definition, I'd appreciate if someone else can look what's wrong because I can't find the error.
