### ISSUE TITLE
Auto-update support for extensions

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#1672]
Specification for add-on devs (both themes and extensions):

Two manifests will need to be provided by an add-on dev:

1) Main add-on manifest:

This will be stored in Playnite add-on repository and will be used by Playnite to display list of all available add-ons to users. It will be a simple YAML file:

```yaml
AddonId: RockstarLibraryIntegration_JN
IconUrl: https://raw.githubusercontent.com/JosefNemec/PlaynitePlugin-RockstarLibrary/master/source/icon.png
ScreenshotUrl: https://raw.githubusercontent.com/JosefNemec/PlaynitePlugin-RockstarLibrary/master/source/icon.png
Type: Library
Description: Automatically imports installed games from Rockstar launcher.
Name: Rockstar Library integration
Author: Playnite
Website: https://github.com/JosefNemec/PlaynitePlugin-RockstarLibrary
```

2) Package list manifest:

Will be referenced by `InstallerManifestUrl` property from main add-on manifest. This will be actually stored where add-on developer chooses, it won't be stored in the main add-on repository as main manifest. The reason being, these can be updated often and would require constant PR reviews from main repository maintainer (me).

This manifest will actually contains list of available add-on versions, including link where to download add-on package:

```yaml
AddonId: RockstarLibraryIntegration_JN
Packages:
  - Version: 1.1
    RequiredApiVersion: 5.3
    PackageUrl: https://github.com/JosefNemec/PlaynitePlugin-RockstarLibrary/releases/download/1.1/RockstarGamesLibrary_1_1.pext
  - Version: 1.2
    RequiredApiVersion: 5.5
    PackageUrl: https://github.com/JosefNemec/PlaynitePlugin-RockstarLibrary/releases/download/1.2/RockstarGamesLibrary_1_2.pext
```

This manifest supports multiple version definitions for cases where add-on developer wants to support multiple Playnite versions with different SDK or theme API versions (in case there's major change to SDK or some breaking change). The minimum supported SDK/Theme API version is defined via `RequiredApiVersion` property.
