### ISSUE TITLE
Add Locale Emulator profile

### ISSUE THREAD

**Issue by ArtexJay** [JosefNemec/Playnite#241]
Add the ability to launch a game with Locale Emulator if installed.

**Comment by ArtexJay** [comment]
Hope this gets implemented somehow, would help a lot for players who downloaded an old or non-localized game.

**Comment by StarKitsune** [comment]
Should look something like this, at least this is how I got Locale Emulator to work:
```
- Name: Locale Emulator
  Website: 'https://pooi.moe/Locale-Emulator/'
  Profiles:
    - Name: Default
      DefaultArguments: '"{ImagePath}"'
      Platforms: [PC]
      ImageExtensions: [exe]
      ExecutableLookup: ^LEProc\.exe
  ```

**Comment by StarKitsune** [comment]
Should have added this earlier, but if you want to add relatively simple access to Locale Emulator's profile manager:
```
- Name: Locale Emulator
  Website: 'https://pooi.moe/Locale-Emulator/'
  Profiles:
    - Name: Default
      DefaultArguments: '"{ImagePath}"'
      Platforms: [PC]
      ImageExtensions: [exe]
      ExecutableLookup: ^LEProc\.exe
      
    - Name: Manage Application Profile
      DefaultArguments: -manage '"{ImagePath}"'
      Platforms: [PC]
      ImageExtensions: [exe]
      ExecutableLookup: ^LEProc\.exe
      
    - Name: Manage Global Profile
      DefaultArguments: -global
      Platforms: [PC]
      ImageExtensions: [exe]
      ExecutableLookup: ^LEProc\.exe
  ```
And for anything else that might be added (this comes straight from LEProc.exe):
```
---------------------------
Locale Emulator Version 2.4.0.0
---------------------------
Welcome to Locale Emulator command line tool.

Usage: LEProc.exe
	path
	-run path [args]
	-runas guid path [args]
	-manage path
	-global

path	Full path of the target application.
guid	Guid of the target profile (in LEConfig.xml).
args	Additional arguments will be passed to the application.

path	Run an application with 
		(i) its own profile (if any) or 
		(ii) first global profile (if any) or 
		(iii) default ja-JP profile.
-run	Run an application with it's own profile.
-runas	Run an application with a global profile of specific Guid.
-manage	Modify the profile of one application.
-global	Open Global Profile Manager.

Have a suggestion? Want to report a bug? You're welcome! 
Go to https://github.com/xupefei/Locale-Emulator/issues.
```
