### ISSUE TITLE
P9: Addons browser doesn't load extensions due to error while deserializing addon manifest

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#2444]
**Describe the bug**
P9: Addons browser doesn't load extensions due to error while deserializing addon manifest

**To Reproduce**
Browse addon extension database. The last log shows that it downloaded this manifest:

```
AddonId: felixkmh_ShortcutSync_Plugin
Packages:
  - Version: 2.1.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-04
    PackageUrl: https://github.com/felixkmh/ShortcutSync-for-Playnite/releases/download/v2.1.0/felixkmh_ShortcutSync_Plugin_2_1_0.pext
    Changelog:
      - localization support. See https://crowdin.com/project/shortcutsync-for-playnite to contribute
      - added german translation
      - updated to QuickSearchSDK 1.4
  - Version: 2.0.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-03
    PackageUrl: https://github.com/felixkmh/ShortcutSync-for-Playnite/releases/download/v2.0.0/felixkmh_ShortcutSync_Plugin_2_0_0.pext
    Changelog:
      - Playnite 9 Beta support, not compatible with Playnite 8!
      - Changed Id, so you need to uninstall before reinstalling!  
  - Version: 1.15.2
    RequiredApiVersion: 5.5.0
    ReleaseDate: 2021-01-07
    PackageUrl: https://github.com/felixkmh/ShortcutSync-for-Playnite/releases/download/v1.15.2/ShortcutSync_1_15_2.pext
    Changelog:
      - Fixed extension not loading in fullscreen mode.
      - Added support for "ExtensionUpdater" plugin in yaml file.
```

**Screenshots**
![image](https://user-images.githubusercontent.com/1389286/132122330-e812fdda-61ee-43fd-8dee-3ae286edb14d.png)

**Diagnostics ID**
40544192-f5b3-42a1-afd0-0193fa24bc27

```
05-09 04:35:32.178|DEBUG|Downloader:Downloading string content from https://raw.githubusercontent.com/felixkmh/DuplicateHider/master/InstallerManifest/felixkmh_DuplicateHider_Plugin.yaml using System.Text.UTF8Encoding encoding.
05-09 04:35:32.603|DEBUG|Downloader:Downloading string content from https://raw.githubusercontent.com/felixkmh/QuickSearch-for-Playnite/master/InstallerManifest/felixkmh_QuickSearch_Plugin.yaml using System.Text.UTF8Encoding encoding.
05-09 04:35:32.900|DEBUG|Downloader:Downloading string content from https://raw.githubusercontent.com/felixkmh/ShortcutSync-for-Playnite/master/InstallerManifest/felixkmh_ShortcutSync_Plugin.yaml using System.Text.UTF8Encoding encoding.
05-09 04:35:33.197|ERROR|BaseServicesClient:Service request error by proxy: An error occurred while deserializing the AddonId property of class Playnite.AddonManifestBase: Cannot deserialize a 'String' from BsonType 'ObjectId'.
05-09 04:35:33.197|ERROR|AddonsViewModel:Failed to get addon list.
System.Exception: An error occurred while deserializing the AddonId property of class Playnite.AddonManifestBase: Cannot deserialize a 'String' from BsonType 'ObjectId'.
   en Playnite.Services.BaseServicesClient.ExecuteGetRequest[T](String subUrl) en E:\Devel\Playnite\source\Playnite\Services\BaseServicesClient.cs:línea 40
...
```
